//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerCors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerCors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve đang có lỗi xảy ra.
        /// </summary>
        public static string Msg_BackEnd_Err {
            get {
                return ResourceManager.GetString("Msg_BackEnd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công.
        /// </summary>
        public static string Msg_Delete_Successfull {
            get {
                return ResourceManager.GetString("Msg_Delete_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trong hệ thống.
        /// </summary>
        public static string Msg_Duplicate_Employee_Err {
            get {
                return ResourceManager.GetString("Msg_Duplicate_Employee_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thành công.
        /// </summary>
        public static string Msg_Insert_Successfull {
            get {
                return ResourceManager.GetString("Msg_Insert_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ngày phải nằm trong phạm vi 1/1/1900 đến 1/1/2100.
        /// </summary>
        public static string Msg_Invalid_Date {
            get {
                return ResourceManager.GetString("Msg_Invalid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị Email không hợp lệ.
        /// </summary>
        public static string Msg_Invalid_Email {
            get {
                return ResourceManager.GetString("Msg_Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị của tiền phải là số dương.
        /// </summary>
        public static string Msg_Invalid_Money {
            get {
                return ResourceManager.GetString("Msg_Invalid_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường nhập phải là một chuỗi kí tự.
        /// </summary>
        public static string Msg_Invalid_NumberField {
            get {
                return ResourceManager.GetString("Msg_Invalid_NumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị số điện thoại nhập không hợp lê.
        /// </summary>
        public static string Msg_Invalid_Phone {
            get {
                return ResourceManager.GetString("Msg_Invalid_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không có trong hệ thống.
        /// </summary>
        public static string Msg_Nocontent {
            get {
                return ResourceManager.GetString("Msg_Nocontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài của trường này vượt quá giá trị cho phép.
        /// </summary>
        public static string Msg_Over_Length {
            get {
                return ResourceManager.GetString("Msg_Over_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin này không được phép để trống.
        /// </summary>
        public static string Msg_Required_Err {
            get {
                return ResourceManager.GetString("Msg_Required_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công.
        /// </summary>
        public static string Msg_Sucessfull {
            get {
                return ResourceManager.GetString("Msg_Sucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công.
        /// </summary>
        public static string Msg_Update_Successfull {
            get {
                return ResourceManager.GetString("Msg_Update_Successfull", resourceCulture);
            }
        }
    }
}
